title: Hand written note
url: "https://qkrwlsghdcjsworlt.github.io/zendwritten/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "http://jinhong-park.github.io/"
footer_text: "Page design by Jin-Hong Park"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "/contact"
