title: JH's notes
url: "https://qkrwlsghdcjsworlt.github.io/zendwritten/"
baseurl: "/zendwritten"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "http://jinhong-park.github.io/"
footer_text: "Page design by Jin-Hong Park"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/zendwritten"
 - name: "Templete"
   link: "resume.pdf"
 - name: "Contact"
   link: "/zendwritten/contact"
